### ISSUE TITLE
Rename Freshheads modules according to usage not webpack entry key

### ISSUE THREAD

**Issue by gnoesiboe** [freshheads/webpack-config-builder#3]
As:

* we want users to be able to use it without knowning a whole lot about Webpack and it's configuration
* some implementations require adjustments to the webpack config on multiple configuration entry keys

## Todo

* [x] Rename Freshheads adapters to match what they do instead of where they go in the webpack configuration
* [x] See if logically some of the Freshheads adapters should be combined (for instance the uglify js and javascript adapter)
* [x] Add additional defaults to `DefaultStackAdapter`
